name: CI Pipeline - Agendify

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, dom, fileinfo, sqlite, pdo_sqlite
        coverage: none

    - name: Copiar .env.example
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar dependencias de Composer
      run: composer install --prefer-dist --no-interaction --no-progress --ignore-platform-req=php

    - name: Generar App Key
      run: php artisan key:generate

    - name: Crear BD SQLite temporal
      run: touch database/database.sqlite
    - name: Instalar Node.js y compilar assets
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build assets con Vite
      run: |
        npm ci
        npm run build

    - name: Ejecutar Migraciones
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    - name: Ejecutar Pruebas con Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/pest